[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
remappings = [
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.2.0/",
    "forge-std/=dependencies/forge-std-1.9.6/src",
]

[soldeer]
remappings_generate = true
remappings_regenerate = false
remappings_version = false
remappings_location = "config"

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.2.0"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
